In [ ]:
from google.colab import files
uploaded = files.upload()

Saving WRI_CLIMATEWATCH_WIDEF.csv to WRI_CLIMATEWATCH_WIDEF.csv

In [ ]:
import pandas as pd

df = pd.read_csv('WRI_CLIMATEWATCH_WIDEF.csv')
df.head()

,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,DATABASE_ID,DATABASE_ID_LABEL,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,A,Annual,AFG,Afghanistan,WRI_CLIMATEWATCH_ALL_GHG_TRANSPORT,Greenhouse gas (GHG) emissions caused by the t...,T_CO2E,Tonnes of CO2-equivalent,WRI_CLIMATEWATCH,Climate Watch,...,5.85,4.33,3.53,4.30,3.31,3.94,4.41,4.55,5.07,5.42
1,A,Annual,AGO,Angola,WRI_CLIMATEWATCH_ALL_GHG_TRANSPORT,Greenhouse gas (GHG) emissions caused by the t...,T_CO2E,Tonnes of CO2-equivalent,WRI_CLIMATEWATCH,Climate Watch,...,6.90,7.88,8.13,8.17,8.09,6.87,7.10,8.10,3.99,7.26
2,A,Annual,ALB,Albania,WRI_CLIMATEWATCH_ALL_GHG_TRANSPORT,Greenhouse gas (GHG) emissions caused by the t...,T_CO2E,Tonnes of CO2-equivalent,WRI_CLIMATEWATCH,Climate Watch,...,2.31,2.51,2.53,2.50,2.37,2.38,2.28,2.26,1.59,1.81
3,A,Annual,ARE,United Arab Emirates,WRI_CLIMATEWATCH_ALL_GHG_TRANSPORT,Greenhouse gas (GHG) emissions caused by the t...,T_CO2E,Tonnes of CO2-equivalent,WRI_CLIMATEWATCH,Climate Watch,...,31.58,35.63,36.57,31.76,35.62,38.75,38.78,36.82,31.59,37.29
4,A,Annual,ARG,Argentina,WRI_CLIMATEWATCH_ALL_GHG_TRANSPORT,Greenhouse gas (GHG) emissions caused by the t...,T_CO2E,Tonnes of CO2-equivalent,WRI_CLIMATEWATCH,Climate Watch,...,46.22,49.23,45.52,47.82,46.80,48.05,49.41,49.09,38.93,48.39

In [ ]:
df.columns

Index(['FREQ', 'FREQ_LABEL', 'REF_AREA', 'REF_AREA_LABEL', 'INDICATOR',
       'INDICATOR_LABEL', 'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'DATABASE_ID',
       'DATABASE_ID_LABEL', 'UNIT_MULT', 'UNIT_MULT_LABEL', 'OBS_STATUS',
       'OBS_STATUS_LABEL', 'OBS_CONF', 'OBS_CONF_LABEL', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021'],
      dtype='object')

In [ ]:
# Check column names first
print(df.columns)

# Create year column list
year_columns = [str(year) for year in range(1990, 2022)]

# Keep only useful columns
df_clean = df[['REF_AREA', 'REF_AREA_LABEL'] + year_columns]

# Rename columns
df_clean = df_clean.rename(columns={
    'REF_AREA': 'Country_Code',
    'REF_AREA_LABEL': 'Country'
})

# Convert wide format to long format
df_long = df_clean.melt(
    id_vars=['Country_Code', 'Country'],
    var_name='Year',
    value_name='Emissions'
)

# Convert data types
df_long['Year'] = df_long['Year'].astype(int)
df_long['Emissions'] = pd.to_numeric(df_long['Emissions'], errors='coerce')

# Remove missing values
df_long = df_long.dropna()

# Remove duplicates
df_long = df_long.drop_duplicates()

# Sort values
df_long = df_long.sort_values(by=['Country', 'Year'])

# Reset index
df_long = df_long.reset_index(drop=True)

# Preview cleaned data
df_long.head()

Index(['FREQ', 'FREQ_LABEL', 'REF_AREA', 'REF_AREA_LABEL', 'INDICATOR',
       'INDICATOR_LABEL', 'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'DATABASE_ID',
       'DATABASE_ID_LABEL', 'UNIT_MULT', 'UNIT_MULT_LABEL', 'OBS_STATUS',
       'OBS_STATUS_LABEL', 'OBS_CONF', 'OBS_CONF_LABEL', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021'],
      dtype='object')

  Country_Code      Country  Year  Emissions
0          AFG  Afghanistan  1990       0.97
1          AFG  Afghanistan  1991       0.93
2          AFG  Afghanistan  1992       0.74
3          AFG  Afghanistan  1993       0.74
4          AFG  Afghanistan  1994       0.73

In [ ]:
df_long.to_csv('cleaned_transport_emissions.csv', index=False)

In [ ]:
from google.colab import files
files.download('cleaned_transport_emissions.csv')

In [ ]:
df_long.describe()

              Year    Emissions
count  6101.000000  6101.000000
mean   2005.611539    67.680172
std       9.216337   501.270467
min    1990.000000     0.000000
25%    1998.000000     0.530000
50%    2006.000000     2.820000
75%    2014.000000    14.610000
max    2021.000000  8493.200000

In [ ]:
df_long.isnull().sum()

Country_Code    0
Country         0
Year            0
Emissions       0
dtype: int64